get http://192.168.100.3:8080/api/asset/hest/76a3e2bc-3fb7-4a35-a41a-d6de915d58f3
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvY3RvcjAyQGdtYWlsLmNvbSIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjU1NGVjMTYyLWI3NTctNDM3Ni04ZGFkLTc3NDRjMTEzNGY1YSIsImlhdCI6MTY1NTM2MzM0MiwiZXhwIjoxNjU2NTYzMzQyfQ.WPDhXswd9YAa06VySZXRM6DvG7az4G6wVycciKef1Ok

   
    
