get http://192.168.100.3:8080/api/asset/hest/6cb6ece9-c2ae-44cc-8cce-81cb80b2234e
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvY3RvcjAxQGdtYWlsLmNvbSIsInJvbGUiOiJkb2N0b3IiLCJpZCI6ImYyMzcwMDQ3LTE2NWQtNGUyYS1hY2U0LWRlN2U1YjM1NjMzZiIsImlhdCI6MTY1NTYyODA3OCwiZXhwIjoxNjU2ODI4MDc4fQ.DC8qOHVwN9MOJ_wgyzGIBqPlVp8bpl9W7_YoB9bt6c4

   
    
